# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56372e6e50f1c61cab6f29d00586230aec43e6978e8f95d9bb15b74472e9a5d22c03d2c7330f4685c2908b87539b3b244b1fcb7fdc372a84bc000dd800739ed1

test:
  secret_key_base: 08c15058821b9fc24284d36343d12df50e3d04061ff276967c71ba638da8a21dfa734948c6a472c439a263387b080eb0125c8cd35802f29c79b708d2d4792376

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
